### ISSUE TITLE
Please add a README File

### ISSUE THREAD

**Issue by aman1k4** [AwenHuang/Compiler#1]

**Comment by haVincy** [comment]
Hello! Which one do you want ? 
1. a readme about the code 
2. a readme how to use 

If you want 1, I can just provide some description from my weak memory. 
If you want 2,  view the makefile in folder, it should have relative command.

**Comment by aman1k4** [comment]
Please add both if you can. If you have any time constraints or anything
else "how to run" would suffice.

TIA

**Comment by haVincy** [comment]
OK ~ which folder(lexer、parser...etc) you want me to add first ?

**Comment by haVincy** [comment]
I add a readme about how to use these program in all four folder. You can take a look.

**Comment by aman1k4** [comment]
@AwenHuang  Thanks a lot !!!
